### ISSUE TITLE
Add conditional checks to disable Legendary Hunt, Monster Pack, and Lost Mount when selecting Wild Hunt on Setup Helper page

### ISSUE THREAD

**Issue by swirle13** [swirle13/The-Witcher-Old-World-Tool-Issues#16]
When selecting Wild Hunt, only Mages, Monster Trail, and Skellige expansions are compatible, the rest are not.

Success criteria:

- When selecting Wild Hunt, all incompatible checkboxes are set to disable
  - Legendary Hunt
  - Monster Pack
  - Lost Mount/Adventure Pack
- Update instructions to Wild Hunt instructions
- Ignore any previously selected fields for incompatible expansions when generating setup steps

**Comment by mjohnson159** [comment]
Added conditional checkbox disabling via https://github.com/mjohnson159/The-Witcher-Old-World-Tool/commit/7060b2a6b7f1402f180261884016e941ff5e26a1

Still need to update instructions for Wild Hunt

**Comment by swirle13** [comment]
Added instructions for Wild Hunt via https://github.com/swirle13/The-Witcher-Old-World-Tool/commit/3c9000ae63c4b183c114d78603dd91acee4b5681

Currently, previously selected checkboxes for Expansions that are not compatible with Wild Hunt are still visually selected, but are set to `false` when sent to `compileSteps()`. Purely a visual bug but toggling them off has been an annoying endeavor for little payoff.
