### ISSUE TITLE
[BUG] Setup Helper (Wild Hunt) remove Step 18e

### ISSUE THREAD

**Issue by Kaligula0** [swirle13/The-Witcher-Old-World-Tool-Issues#72]
Setup Helper with Wild Hunt issue: Steps 18e and 19 eliminate each other. From what I know the 18e should be removed.

![image](https://github.com/swirle13/The-Witcher-Old-World-Tool-Issues/assets/3950811/9f514183-f5f3-4294-98c7-b6ee17ed9763)

**Comment by swirle13** [comment]
You're totally correct. I unabashedly put all the blame on pkitty, whose content I "borrowed" from his guide on BGG to populate these! No, but really, I had to put the logic in to separate these and totally missed that. I'll get that updated.

**Comment by swirle13** [comment]
Fixed via https://github.com/swirle13/The-Witcher-Old-World-Tool/commit/361b3fce3b5985c94c61e557c4e773e77dfedec4
