### ISSUE TITLE
[ENHANCEMENT][MAINTENANCE] Link in main repo's description

### ISSUE THREAD

**Issue by Kaligula0** [swirle13/The-Witcher-Old-World-Tool-Issues#73]
Please add a link to your tool in the main repo's description – just like it's in this Issues' repo

**Comment by swirle13** [comment]
Fixed via your PR https://github.com/swirle13/The-Witcher-Old-World-Tool/commit/2d0d9fb4c26d2bbd1a231af8599e4bdbdc99c4a9

I also added it via the "website" attribute in Repository Details (a nice checkbox to use the github page site made it really easy :P) 
<img width="361" alt="image" src="https://github.com/swirle13/The-Witcher-Old-World-Tool-Issues/assets/9778474/784d4f10-ace8-434f-8df2-6b3a764ab2be">

**Comment by Kaligula0** [comment]
>  I also added it via the "website" attribute in Repository Details (…)

That's the place I was thinking about! :) Thank you

You may also include info that it is an online tool, like I PR-ed in README.md
